### ISSUE TITLE
will update jieba 0.38?

### ISSUE THREAD

**Issue by nelson6699520** [anderscui/jieba.NET#1]

**Comment by anderscui** [comment]
@nelson6699520 嗯，没注意到jieba有更新。。。这个要更新的，主要根据jieba的更新内容。

另外，请问有分词相关的其它需求吗？如果可以，还是希望.NET版本有点自己的内容：）

**Comment by nelson6699520** [comment]
我認為jieba缺乏一些較為實用的分詞功能，例如：分詞器沒有stop word; 中文數字轉阿拉伯數字；字典同義詞功能。(如有請告之）

同時我發現jeiba.net佔用記憶體較大，不知道可否優化，期望它越來越完善。

**Comment by anderscui** [comment]
@nelson6699520 谢谢，stop words这里需要改进一下，我也有同感；同义词的话需要找一个好的corpus，容我慢慢看：）

**Comment by Linusp** [comment]
@anderscui 同义词的话  [Open Multilingual Wordnet](http://compling.hss.ntu.edu.sg/omw/) 中就可以，只是里面的内容质量怎么样不太清楚

```python
from nltk.corpus import wordnet as wn

for syn in wn.synsets(u'快乐'), lang='cmn'):
    print u'/ '.join(syn.lemma_names(lang='cmn'))
```
结果
> 快乐/ 愉快
> 喜悦/ 快乐/ 快活/ 欢乐/ 欢喜/ 高兴
> 好运气/ 幸福/ 幸运/ 快乐

**Comment by anderscui** [comment]
@nelson6699520 @Linusp 请问你们觉得什么场景下面需要返回同义词？返回的结果希望是什么？

比如：他看起来很高兴。

这句话分词之后，有一个“高兴”，如果我要查询它的同义词，可以用这样的方式：
```c#
var w = "高兴";
var syns = dict.synonym(w);
// syns => { "快乐", "欢喜", "换了" } 
```

还是说分词之后直接就包含了同义词？

**Comment by nelson6699520** [comment]
我期望是分词后包含同义词。
