### ISSUE TITLE
我想咨询一下 中文分词有关问题 

### ISSUE THREAD

**Issue by Lumia1020** [anderscui/jieba.NET#10]
我用的是 jieba.NET 版本，我现在遇到一个问题
比如  我想搜索的关键字为：糖尿病药 、糖尿病药品
如果使用自带词库 
糖尿病药分词结果： 糖尿/糖尿病/药
糖尿病药品分词结果：糖尿/糖尿病/药品

因为现在我做的是药品类电商搜索，这时候会遇到一个问题，如果把药、药品这两个字分出来，这样匹配的结果会相当不准确（因为在生成索引的时候，药品在多个域中含有）

还有一个问题 想咨询一下 就是在结巴分词词库中 哪个词频 我还是没搞清楚具体作用（十分抱歉我是新手）

**Comment by Lumia1020** [comment]
还有一个问题 我通过 Lucene.NET 结合结巴分词 建立的索引 
最近搜索药品  得出的结果为 4000 多条
而搜索药 得出的结果反而只有 500 多条  
因为两者搜索条件都是一样的  
搜索针对的域也是一样的

**Comment by anderscui** [comment]
@Lumia1020 我的理解，词频只影响分词的结果，这会导致“药”和“药品”的不同。

**Comment by Lumia1020** [comment]
我还想问个问题  JiebaSegmenter.DeleteWord(word)  就是这个方法  将删除一个词 使其不能被分出来 
我想问一下  比如 感冒药 这三个字 是我搜索的  我这时候调用 JiebaSegmenter.DeleteWord(“感冒药”) 意思
用户在搜索 感冒药 这三个字时
不会被结巴分词组件分成  感冒/感冒药  分出来的结果只有感冒药这一种么

**Comment by anderscui** [comment]
如果DeleteWord正常工作的话，删除感冒药后，”感冒药“的分词结果应该是感冒/药，因为”感冒药“不再被当做一个词了。

**Comment by anderscui** [comment]
@Lumia1020 最后你是如何处理的？这里是否可以通过在Lucene中添加同义词来解决？
