### ISSUE TITLE
什么时候项目能支持.net core?

### ISSUE THREAD

**Issue by alex521** [anderscui/jieba.NET#11]

**Comment by anderscui** [comment]
@alex521 是在什么平台上使用？Windows和Linux？我现在手头上比较方便的是Mac环境，能不能帮忙测试下其它平台？十一之后，我会把现在的几个issue一起处理下：）

**Comment by alex521** [comment]
我在windows上开发

**Comment by anderscui** [comment]
@alex521 那没问题，我也可以在Windows上测试

**Comment by guxl** [comment]
我这里环境比较全。也希望能得到 支持.net core 的版本。

**Comment by wddpct** [comment]
@anderscui  是否支持了.net core呢

**Comment by linezero** [comment]
支持.NET Core 版 https://github.com/linezero/jieba.NET @anderscui

**Comment by anderscui** [comment]
@linezero 赞：）
