### ISSUE TITLE
Error in ASP.NET

### ISSUE THREAD

**Issue by davidqing2000** [anderscui/jieba.NET#13]
在ASP.NET 环境下，创建以下两个提取关键词的CLASS,总是报错。
web.config 文件中已增加以下设定
<add key="JiebaConfigFileDir" value="dict folder"/>

JiebaNet.Analyser.TfidfExtractor tf = new TfidfExtractor();
JiebaNet.Analyser.TextRankExtractor tr = new TextRankExtractor();

“System.MissingMethodException”类型的异常在 MRAnalysis.dll 中发生，但未在用户代码中进行处理

其他信息: 找不到方法:“Void JiebaNet.Segmenter.JiebaSegmenter..ctor(Boolean)”。

请问应如何解决？

**Comment by anderscui** [comment]
@davidqing2000 我这两天看看。

**Comment by shadowlightqywx** [comment]
Nuget里面的只有在0.38.2版本中出现这个问题，降级到0.38.1就没事了，还是希望能尽快解决吧

**Comment by anderscui** [comment]
@davidqing2000 , @shadowlightqywx 应该是NuGet发布包的问题，请更新到最新版本。
