### ISSUE TITLE
“JiebaNet.Segmenter.JiebaSegmenter”的类型初始值设定项引发异常。

### ISSUE THREAD

**Issue by GnailGnepGnaw** [anderscui/jieba.NET#14]
想请问一下 我把Resources文件夹复制到了我的项目目录下，然后在web配置文件里添加了绝对路径，但是还是报这个错误

![image](https://cloud.githubusercontent.com/assets/13447881/20657982/e85813ee-b574-11e6-8b84-7807dfc0de99.png)

设置路径 ：
`  <appSettings>
	  <add key="JiebaConfigFileDir" value="E:\Projects\TFS\Leading\Main\PdaSite\JiebaConfig"/>
  </appSettings>`

请问是我哪里设置的有问题吗？

**Comment by anderscui** [comment]
@GnailGnepGnaw 看起来应该没问题，我这里在ASP.NET MVC项目中测试是可以的。

**Comment by GnailGnepGnaw** [comment]
重新启动了IDE,还是同样的路径,就可以了,感觉是电脑的问题,现在已应用到实际项目,感谢作者。
