### ISSUE TITLE
调用DeleteWord和AddWord发现只在程序执行期间有效！！！

### ISSUE THREAD

**Issue by huigy** [anderscui/jieba.NET#19]
调用DeleteWord和AddWord发现只在程序执行期间有效！是bug还是就这样，但总觉得不方便是不是要自己修改代码实现对字典文件直接做修改！？

**Comment by anderscui** [comment]
@huigy 按照Python版的实现，这个确实是不会保存到字典的。原字典是经过统计得来的，最好不要把自定义字典和它混起来。这样，建议把需要Add和Delete的字典保存在单独的文件中，运行时动态加载和删除吧。

**Comment by huigy** [comment]
明白了，不行稍后自己实现把，谢谢。
