### ISSUE TITLE
搜索引擎模式無法使用

### ISSUE THREAD

**Issue by aisen0921** [anderscui/jieba.NET#22]
`            var cc = segmenter.CutForSearch(this.txtTest.Text);
            foreach (var r in cc)
            {
                Console.WriteLine(r);
            }
`
原始
`小明碩士畢業於中國科學院計算所，後在日本京都大學深造`
輸出為
`小明
碩士
畢業
於
中國
科學院
計算
所
，
後
在
日本
京都
大學
深造`

跟我看到的範例結果都不一樣
找不到是哪裡出錯?

**Comment by anderscui** [comment]
@aisen0921 等我后面有时间看看，看起来可能是因为繁体中文和简体中文的字典不同。

**Comment by anderscui** [comment]
@aisen0921 这个问题应该是因为使用词典不同导致的，默认词典偏向于简体中文，比如有“京都大学”但没有“京都大學”。建议使用ExtraDicts/dict.txt.big这个词典，用这个文件的内容override默认的dict.txt文件内容。
