### ISSUE TITLE
哈工大同义词词典有使用上吗？

### ISSUE THREAD

**Issue by penhauer-xiao** [anderscui/jieba.NET#23]
哈工大同义词词典有使用上吗？ 拿来干什么用的，如何用呢？

**Comment by anderscui** [comment]
@penhauer-xiao 本来是想搜索时用的，你有什么地方用到吗？

**Comment by penhauer-xiao** [comment]
@anderscui  打算文章去重用，你用到了吗？

**Comment by anderscui** [comment]
@penhauer-xiao .NET版本暂时还没用到，因为工作主要用Python。同义词功能还是比较常用的，可以考虑加上。

**Comment by penhauer-xiao** [comment]
@anderscui  你加上了吗？

**Comment by anderscui** [comment]
考虑在ElasticSearch上尝试加一下，这里面和jieba就不太一样了。你可以把你的使用场景写出来吗？我做个参考：）

**Comment by penhauer-xiao** [comment]
@anderscui   参考：https://github.com/gensmusic/simhash/issues/3
