### ISSUE TITLE
Please specify fileaccess.read when load dict

### ISSUE THREAD

**Issue by buptconnor** [anderscui/jieba.NET#26]
hi，我在Azure部署的时候一直遇到这样的问题
> ASP.NET is not authorized to access the requested resource “E:\sitesroot\0\Resources\dict.txt”

后来检查源码，发现问题是WordDictionary.cs第42行
> var stream = new FileStream(MainDict, FileMode.Open);

我把这里修改成了如下，解决了问题。
> var stream = new FileStream(MainDict, FileMode.Open, FileAccess.Read);

如果不添加FileAccess.Read，在本地运行时不会有问题；如果服务器部署IIS时，会需要修改IIS运行权限；部署到azure等云上时，修改权限非常的麻烦，建议方便的话可以修改一下。

**Comment by anderscui** [comment]
@buptconnor 谢谢你的建议：）这样修改后，本地、服务器和Azure上都可以运行的是吗？

**Comment by buptconnor** [comment]
@anderscui 应该是可以的。这样修改能避免在部署到iis时，以匿名用户身份执行时没有权限打开的问题，也不会影响本地运行。我现在部署到azure上是可以了。

**Comment by anderscui** [comment]
@buptconnor 好的，后面会检查一下这里，在下次更新时改好：）

**Comment by anderscui** [comment]
@buptconnor 我刚才检查了一下代码，你说的这一行没有找到，现在对应的是第43行：

`var sr = new StreamReader(MainDict, Encoding.UTF8)`

您可以再确认一下吗？
