### ISSUE TITLE
Nuget下载安装后，Tfidf使用报错

### ISSUE THREAD

**Issue by calmzealA** [anderscui/jieba.NET#27]
1. PM> Install-Package jieba.NET
2. 复制package下resource目录到项目目录。
3.JiebaNet.Analyser.TfidfExtractor extract = new JiebaNet.Analyser.TfidfExtractor();
步骤三报错 
““System.NullReferenceException”类型的异常在 JiebaNet.Analyser.dll 中发生，但未在用户代码中进行处理
其他信息: 未将对象引用设置到对象的实例。”

环境为asp.net 4.5。 步骤二的dic目录已经确认正常。

**Comment by calmzealA** [comment]
> var s = MainDictFile;
> JiebaNet.Segmenter.JiebaSegmenter seg = new JiebaNet.Segmenter.JiebaSegmenter();
> var seg1 = seg.Cut(s1);
> var segstr = string.Join(" ",seg1);
> 
> JiebaNet.Analyser.TfidfExtractor extract = new JiebaNet.Analyser.TfidfExtractor();

只有最后一句报错，前面segmenter分词是正常的

**Comment by calmzealA** [comment]
调试了下源代码，我pull一个吧

**Comment by anderscui** [comment]
@calmzealA 已经merge。
