### ISSUE TITLE
请问有没有计算词频的功能？怎么调用

### ISSUE THREAD

**Issue by ZoeM2016** [anderscui/jieba.NET#29]
请问有没有计算词频的功能？怎么调用

**Comment by anderscui** [comment]
@ZoeM2016 你是说统计一段文本的词频吗？目前没有，不过分词之后可以自己简单地统计出来。或者你有别的需求请先写下来，后面慢慢加上。

**Comment by ZoeM2016** [comment]
好的，谢谢，但是我还有一个问题，为什么我自己添加了用户字典后可以成功分词，但是词性标注却没有按我用户字典中的标注，而是全部变成了/x

**Comment by anderscui** [comment]
@ZoeM2016 词性标注的问题，你的代码是？我这边没有重现
