### ISSUE TITLE
请问关键词提取如何限定仅提取某些词

### ISSUE THREAD

**Issue by lanochan** [anderscui/jieba.NET#31]
您好，dict自定义后 可以根据限定的词语进行分词。
请问提取关键词时，如何仅提取某些词呢？比如 我只需要提取出  MP3，MP4，音箱 此类词语。
SetIdfPath 是否仅影响排序？尝试多次得不到想要的结果。
技术有限，源码看的不是很明白。感谢！！！

**Comment by anderscui** [comment]
@lanochan 是的，仅影响排序。建议自己使用一个辅助字典对结果进行过滤。
