### ISSUE TITLE
Tokenize：返回词语在原文的起止位置有错误

### ISSUE THREAD

**Issue by pfwu2018** [anderscui/jieba.NET#32]
anders 你好！Tokenize：返回词语在原文的起止位置（StartIndex,EndIndex）是不是有较大的问题，
例如 var s = "永和服装饰品   有限公司"，就是在中文串中插入几个空格，那么分词得到的Token,"有限","公司"的StartIndex,EndIndex就不是原文的起止位置了。
再比如，英文  var s = "Issues help repositories track bugs, enhancements, and ideas. You can submit new bugs, requests, or join the discussion."
Tokenize以后，除Issues这个词，其他的token的StartIndex,EndIndex全都不是原文的起止位置了。

在与Lucene.net集成时，设置Term的Offset使用了  offsetAtt.SetOffset(token.StartIndex, token.EndIndex)
那么再使用Lucene.net Highlight做高亮显示时，使用的Term的Offset作为位置值，就是错误的，会出现高亮了其他词，而不是要搜索的这个Term。

所以，在JiebaSegmenter.cs这个程序文件中，好像不应该使用下面这样的代码(原py版本好像也是这样的)，
                    var width = w.Length;
                    result.Add(new Token(w, start, start + width));
                    start += width;

但具体怎么做，我琢磨了源代码很长时间，也还没有解决方法，看看 Anders有没有好的方法。谢谢

**Comment by anderscui** [comment]
@pfwu2018 很感谢你发现的这个bug，我找到出错的地方了，很快会更新上去。
