### ISSUE TITLE
Resource path 配置如果加一个code API就好了。

### ISSUE THREAD

**Issue by v-chfeng** [anderscui/jieba.NET#33]
因为使用config配置有局限性。我使用jieba的时候的工程只能打包成dll, 然后上传到server，无法更改主程序的config。

所以个人认为加一个code API会更好一些。

**Comment by anderscui** [comment]
@v-chfeng 好的，我最近改进一些这里。可不可以写一下你期望的API接口以及用法是什么样的？比如方法名和调用流程什么的。

**Comment by anderscui** [comment]
@v-chfeng  好的，我最近会改进一些这里。可不可以写一下你期望的API是什么样的？比如方法名和调用逻辑什么的。

**Comment by tigerphc** [comment]
我也觉得这个很不方便，dll 如何修改主程序的配置？
而且我在主程序里面的app.config里面添加如下内容，然后Resource里面的文件放进去后发现不起作用。。。
<appSettings>
    <add key="JiebaConfigFileDir" value="C:\jiebanet\config" />
</appSettings>

**Comment by anderscui** [comment]
@tigerphc 请试一下新版本。
