### ISSUE TITLE
关于去除停用词后进行词频统计

### ISSUE THREAD

**Issue by Yista** [anderscui/jieba.NET#34]
有幸能使用到大佬做的jieba分词。
在使用的过程遇到一个问题，就是载入停用词后，使用TfidfExtractor中的ExtractTags(txt,10)对txt进行分词，获得10个string数据是已经按词频排序好的吗？能具体获得使用停用词后分出来的各个词的词频吗？因为我和直接用segment.cut方法获得的结果用counter获得词频，然后获取Mostcommon（100）的结果进行对比，发现有几个词的先后顺序略有差异。
![image](https://user-images.githubusercontent.com/35027490/38005630-16fae0e6-3274-11e8-9ea9-9131a4b8035d.png)
![image](https://user-images.githubusercontent.com/35027490/38005640-26c75162-3274-11e8-8c8e-2ac505ef14f0.png)
第一张图是用extracttags获得的结果（10个），第二张图是直接cut后统计的结果，停用词为jieba.net中附带的stopwords_zh_hit.txt文件。

**Comment by KeliBox** [comment]
略有差异，相当正常啊。tfidf跟tf是不同演算。

**Comment by Yista** [comment]
懂了，多谢两位的解答。
