### ISSUE TITLE
为什么.Net版本的结巴需要4.5的FrameWork这个高版本啊，4.0不好吗？客户端使用4.5太高了

### ISSUE THREAD

**Issue by minren118** [anderscui/jieba.NET#35]
想在Excel插件上引用结巴，发现FrameWork要4.5版本，现在插件做的是4.0的，难道就无缘用结巴了，4.0大部分功能都有了吧，为何不实现为4.0的？一些异步方法可以通过BCL单独在nuget上下载啊

**Comment by anderscui** [comment]
@minren118 这个也没有什么特别的原因，就是当时做的时候手头最熟悉的是4.5，就用了。后面看看能否改一下。

**Comment by minren118** [comment]
我把github代码拉到本地，改了.net framework版本，可以4.0生成成功，麻烦在nuget上也重新编译一下，方便项目调用，非常感谢。

**Comment by minren118** [comment]
最好做个强类型签名，这样子可以方便项目调用时把dll放到其他位置用AppDomain.CurrentDomain.AssemblyResolve事件来加载，我的项目用clickonce部署，不把引用dll放别的位置，每次版本更新都给我复制一份dll到客户机上麻烦

**Comment by anderscui** [comment]
@minren118 谢谢反馈，我尽快看一下。

**Comment by zhuozhang19911122090807** [comment]
> 
> 
> 我把github代码拉到本地，改了.net framework版本，可以4.0生成成功，麻烦在nuget上也重新编译一下，方便项目调用，非常感谢。

vs2013打开可以吗，改了.net framework版本，4.0没有生成成功呢？

**Comment by zhuozhang19911122090807** [comment]
.net framework4.0可以用吗

**Comment by minren118** [comment]
我忘记当时怎么搞的把它搞到.net 4.0里可用了，可能是我自己重新编译了。将结巴用到Excel中来，感谢结巴这么优秀的轮子。

这是我的功能介绍：https://www.jianshu.com/p/56a0616125fa

 

发件人: zhuozhang19911122090807 <notifications@github.com> 
发送时间: 2019年10月22日 10:53
收件人: anderscui/jieba.NET <jieba.NET@noreply.github.com>
抄送: minren118 <190262897@qq.com>; Mention <mention@noreply.github.com>
主题: Re: [anderscui/jieba.NET] 为什么.Net版本的结巴需要4.5的FrameWork这个高版本啊，4.0不好吗？客户端使用4.5太高了 (#35)

 

.net framework4.0可以用吗

**Comment by anderscui** [comment]
@minren118 现在已经支持了：）
