### ISSUE TITLE
无法识别混合有符号、字母、汉字的词？

### ISSUE THREAD

**Issue by 23df** [anderscui/jieba.NET#42]
在处理医学病历，“该患者窦性心律不齐，心电图示短P-R间期”，已经向自定义词典中添加了“窦性心律不齐”和“短P-R间期”，遗憾的是“短P-R间期”无法正确识别，被拆成了“短/P/-/R/区间”。

**Comment by 23df** [comment]
在.net平台，我在调用结巴分词之前，使用自定义规则（如正则表达式）对可能分错的词条做了预处理，比如说替换，在结巴分词之后再改回原来的。

**Comment by juhuahuang** [comment]
谢谢，是个好办法。不知道jieba有没有可能从根本上解决这个问题。

**Comment by anderscui** [comment]
@23df 已修复。
