### ISSUE TITLE
对类似“艾尔肯·吐尼亚孜”切词，即使添加了自定义词典，也无法把这个人名切出来 

### ISSUE THREAD

**Issue by juhuahuang** [anderscui/jieba.NET#43]
我把这个名字“艾尔肯·吐尼亚孜”加到了词典中并且用segmenter.LoadUserDict() 加入了词典，对这句话
艾尔肯·吐尼亚孜新疆阿克苏人
切出来的结果是
艾尔肯/·/吐/尼亚/孜/新疆/阿克苏/人

但是如果名字里没有·，比如将”一个不在字典中的名字“放入字典，就可以正确切出来，请问这是什么原因，我该如何应对名字中存在·的情况？

**Comment by anderscui** [comment]
@juhuahuang 已经修复。
