### ISSUE TITLE
关于分词 我在词典中删除了 “天半” 但是分词还是在一起

### ISSUE THREAD

**Issue by wjm23714** [anderscui/jieba.NET#46]
你好，我在词典中删除了 “天半” 但是分词的时候还是认为是一个词组，请问这个要怎么处理。谢谢

**Comment by anderscui** [comment]
@wjm23714  请问你的原始输入句子是什么？我在C#和Python版本里都不能重现。

**Comment by wjm23714** [comment]
> @ wjm23714请问 你的原始输入句子是什么？我在C＃和Python版本里都不能重现。

那会我输入的是2天半 分词之后 显示的还是“天半”

**Comment by anderscui** [comment]
@wjm23714 那再试一下？应该是没有这个问题的。
