### ISSUE TITLE
分词功能.Cut()出错

### ISSUE THREAD

**Issue by mander199** [anderscui/jieba.NET#49]
当调用 loadUser.Cut("简历名称JAVA后端")，即：“简历名称JAVA后端”无空格的情况下，报错“loadUser.Cut("简历名称JAVA后端")”引发了类型“System.NullReferenceException”的异常；
当调用 “loadUser.Cut("简历名称JAVA 后端")，即：“简历名称JAVA[空格]后端”有空格的情况下，不报错。
说明：在vs2017下。

已经解决：使用loadUser.Cut("stringparam",true)

**Comment by mander199** [comment]
已经解决：使用loadUser.Cut("stringparam",true)

**Comment by anderscui** [comment]
@mander199 这个issue似乎不能重现。
