### ISSUE TITLE
关于词典路径在asp.net环境的问题

### ISSUE THREAD

**Issue by attsion** [anderscui/jieba.NET#5]
在winform或者console下是没有问题的，但如果在asp.net mvc下使用jieba.net 会去iisexpress 的安装目录下下去寻找词典。

**Comment by anderscui** [comment]
嗯，后面想改进一下路径相关的问题，包括你说的这个问题，以及当前需要配置多个路径的问题，希望能够使配置更简单明了。请问有什么建议吗？

**Comment by attsion** [comment]
我临时是这么解决的：
`using System.Configuration;
using System;
namespace JiebaNet.Segmenter
{
    public class ConfigManager
    {
        public static string domin = AppDomain.CurrentDomain.BaseDirectory;
        public static string MainDictFile
        {
            get { return domin + ConfigurationManager.AppSettings["MainDictFile"] ?? @"Resources\dict.txt"; }
        }

        public static string ProbTransFile
        {
            get { return domin + ConfigurationManager.AppSettings["ProbTransFile"] ?? @"Resources\prob_trans.json"; }
        }

        public static string ProbEmitFile
        {
            get { return domin + ConfigurationManager.AppSettings["ProbEmitFile"] ?? @"Resources\prob_emit.json"; }
        }

        public static string PosProbStartFile
        {
            get { return domin + ConfigurationManager.AppSettings["PosProbStartFile"] ?? @"Resources\pos_prob_start.json"; }
        }

        public static string PosProbTransFile
        {
            get { return domin + ConfigurationManager.AppSettings["PosProbTransFile"] ?? @"Resources\pos_prob_trans.json"; }
        }

        public static string PosProbEmitFile
        {
            get { return domin + ConfigurationManager.AppSettings["PosProbEmitFile"] ?? @"Resources\pos_prob_emit.json"; }
        }

        public static string CharStateTabFile
        {
            get { return domin + ConfigurationManager.AppSettings["CharStateTabFile"] ?? @"Resources\char_state_tab.json"; }
        }
    }
}`
建议仅对词典文件夹路径配置下就好，而且最好能在类的构造函数中提供一个重载来免配置文件的方式去处理词典路径。

**Comment by anderscui** [comment]
@attsion 现在配置改成这样的了，只需要目录来配置：

```xml
<appSettings>
    <add key="JiebaConfigFileDir" value="C:\jiebanet\config" />
</appSettings>
```

**Comment by attsion** [comment]
回头试试，请问路径里面能填入相对路径吗？web下会不会又跑去找iisexpress的安装目录了？

**Comment by anderscui** [comment]
@attsion Web的情况，相对路径还是那样会有问题，这次没有特别处理：）

**Comment by attsion** [comment]
恩恩 那就太感谢了，现在web是大势所趋啊。

**Comment by alex521** [comment]
web 下有处理的方法吗？ 绝对路径在云服务器上没办法设。

**Comment by anderscui** [comment]
@alex521 那么就像 @attsion 那样，用相对于AppDomain的路径了？

**Comment by anderscui** [comment]
@attsion , @alex521 ，刚刚修改了，如果是相对路径，那么会使用相对于AppDomain的路径。

**Comment by guxl** [comment]
我的建议是，不考虑配置文件！原因如下：

1. 客户端对Jieba.Net关于配置文件的需求各不相同，不能保证客户端的要求，就不如把权利交给客户端。
2. 如果要支持.net Core， .net Core 的配置系统和现有方式完全不同，现在考虑这些会非常尴尬。
3. 如果要将读取配置文件的任务放倒JiaBa.net中，这就相当于分词组件干了它份外的事，不符合单一职责的设计原则，即便是想要帮助客户端多做一些事情，也应该以扩展或工具的形式，放到 ｀`JiebaSegmenter`之外，这样的话，如果扩展(或工具)类符合客户端的要求，客户端自己调用，如果不符合客户端的要求，客户端可以自己实现。

__建议的方式：__
任何需要外部资源(1)的地方，都提供便于客户端注入的接口(2)，如果怕客户端会感到复杂，就提供一个`JiebaSegmenterBuilder`生成器(3)。

（1）外部资源，包括词典、停用词、甚至是 [todo.md](https://github.com/anderscui/jieba.NET/blob/master/docs/todo.md) 中所提到的 logging、cache等一些组件，最终目的就是实现 Ioc 和 Component化。
（2）建议上面提到的资源，以属性的方式由客户端注入，例如
``` csharp
public class JiebaSegmenter
{
    public void UseDictPath(DirectoryInfo dictDir);
}
```
（3）如果参数实在是复杂，就弄一个builder，客户端调用如下：
``` csharp
public JiebaSegmenter BuildJiebaSegmenter()
{
    return new JiebaSegmenterBuilder()
        .WithDict.UseDefault()
        .WithStopWords.FormFile(stopWrodsFile)
        .WithLogger.UseConfig(logPosition, loglevel,etc)
        .Build();
}
```

**Comment by anderscui** [comment]
@guxl 谢谢，你的建议很有帮助。我现在的工作已经是不用.NET了，对于.NET core虽然有兴趣，但恐怕没时间专门去学。感觉你对.NET是很熟悉的，能否帮忙做些这方面的开发？

**Comment by sgf** [comment]
@anderscui
与时俱进啊 老铁，支持.net core 大势所趋啊，而且其实 .net core 和.net framework 大部分没啥区别。

**Comment by anderscui** [comment]
@guxl 现在可以直接通过代码设置了。

@sgf 已经同时支持net40和netstandard2.0。
