### ISSUE TITLE
关于Jieba.net引用MVC框架时候出错的问题

### ISSUE THREAD

**Issue by hhtao** [anderscui/jieba.NET#53]
我是一个新手，正在研究MVC系统框架，前几天刚刚把jieba项目启动来，今天加入MVC框架后，发现无法正常启动，系统能够正常编译，我在index视图加入如下代码
 JiebaSegmenter jiebaSegmenter = new JiebaSegmenter();
  jiebaSegmenter.Cut("我就试试");
能够正常编译，启动后报错信息如下：
System.IO.FileLoadException
  HResult=0x80131040
  Message=未能加载文件或程序集“Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=null”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)
  Source=JiebaNet.Segmenter
  StackTrace:
   在 JiebaNet.Segmenter.FinalSeg.Viterbi.LoadModel() 在 D:\jieba.NET-master\src\Segmenter\FinalSeg\Viterbi.cs 中: 第 86 行
   在 JiebaNet.Segmenter.FinalSeg.Viterbi..ctor() 在 D:\jieba.NET-master\src\Segmenter\FinalSeg\Viterbi.cs 中: 第 28 行
   在 JiebaNet.Segmenter.FinalSeg.Viterbi.<>c.<.cctor>b__14_0() 在 D:\jieba.NET-master\src\Segmenter\FinalSeg\Viterbi.cs 中: 第 15 行
   在 System.Lazy`1.CreateValue()

请版主帮忙看看，指点一下，谢谢！

**Comment by sgf** [comment]
你这个很可能是 因为 下载了 jieba.net 项目，然后又下载了 已经编译好的 jieba.dll 导致的 dll版本不一致问题。解决方案估计很简单，要么删掉 项目，只引用dll。 要么只引用项目，不引用dll(也不要保留，因为jieba项目会自动生成dll)。

另外问题解决了建议关掉issue。

**Comment by anderscui** [comment]
@sgf 谢谢解答：）
