### ISSUE TITLE
自定义词典路径的正确设置方法是什么？

### ISSUE THREAD

**Issue by holypenguin** [anderscui/jieba.NET#55]
console程序，设置了多种自定义词典的路径均不能正常分词，但是修改主词典或使用addword可以正常分词

尝试了以下几种：
1.绝对路径，例如 d:\my_dict.txt
2.相对路径，例如 my_dict.txt ，文件放在 Resources目录下 或 debug目录下均不成功
3.相对路径，录入 Resources\my_dict.txt, 文件放在 Resources目录下

自定义词典格式为：
二号谈话间 732 zg
一号谈话间 10 nz

初始化代码为：
segmenter = new JiebaSegmenter();
segmenter.LoadUserDict(@"d:\my_dict.txt");

测试程序输入：二号谈话间 
返回结果：
【全模式】：二号/ 谈话/ 间
【精确模式】：二号/ 谈话/ 间
【搜索引擎模式】：二号/ 谈话/ 间

请问该如何设置才能让自定义词典生效？

**Comment by binzhou75** [comment]
不一定是路径问题，检查一下自定义词典文件的编码格式，一定要是UTF-8才行。

**Comment by died** [comment]
如果你是在debug時載入dict，可以試著用上兩層的方式去抓
![img](https://i.imgur.com/YBS9WZu.png)
