### ISSUE TITLE
关于词典路径在 .netcore 环境的问题

### ISSUE THREAD

**Issue by lianggx** [anderscui/jieba.NET#58]
目前测试样例下使用的版本是：JiebaNet.Segmenter 1.0.6，每次启动总是需要很长时间去查找加载字典目录，关键是还找不到。
示例代码：
            var seg = new JiebaNet.Segmenter.JiebaSegmenter();
            string path = @"E:\sort\SortManage\jieba-resource";
            seg.LoadUserDict(path);
            services.AddSingleton<JiebaNet.Segmenter.JiebaSegmenter>(seg);
抛出异常：
System.TypeInitializationException:“The type initializer for 'JiebaNet.Segmenter.JiebaSegmenter' threw an exception.”
DirectoryNotFoundException: Could not find a part of the path 'E:\sort\SortManage\SortManage.API\Resources\prob_trans.json'.

检查配置文件实体类：
JiebaNet.Segmenter.ConfigManager
构造函数：
public static string ConfigFileBaseDir
        {
            get
            {
#if !(NETSTANDARD1_0 || NETSTANDARD2_0)
                var configFileDir = ConfigurationManager.AppSettings["JiebaConfigFileDir"] ?? "Resources";
                if (!Path.IsPathRooted(configFileDir))
                {
                    var domainDir = AppDomain.CurrentDomain.BaseDirectory;
                    configFileDir = Path.GetFullPath(Path.Combine(domainDir, configFileDir));
                }
#else
                var configFileDir = "Resources";
#endif
                return configFileDir;
            }
        }

上面已经写死了配置文件目录为：Resources ，无法使用自定义目录，导致初始化 JiebaSegmenter 实例的时候无法加载字典，是否考虑把初始化作为接口公开，由客户端决定何时何地使用任意目录进行字段目录的配置。
以方便加载字典和初始化实例。

**Comment by anderscui** [comment]
@lianggx 在readme的“安装和配置”一节有说明，看看能否解决你的问题。

**Comment by xskingdeekis** [comment]
> 目前测试样例下使用的版本是：JiebaNet.Segmenter 1.0.6，每次启动总是需要很长时间去查找加载字典目录，关键是还找不到。
> 示例代码：
> var seg = new JiebaNet.Segmenter.JiebaSegmenter();
> string path = @"E:\sort\SortManage\jieba-resource";
> seg.LoadUserDict(path);
> services.AddSingleton<JiebaNet.Segmenter.JiebaSegmenter>(seg);
> 抛出异常：
> System.TypeInitializationException:“The type initializer for 'JiebaNet.Segmenter.JiebaSegmenter' threw an exception.”
> DirectoryNotFoundException: Could not find a part of the path 'E:\sort\SortManage\SortManage.API\Resources\prob_trans.json'.
> 
> 检查配置文件实体类：
> JiebaNet.Segmenter.ConfigManager
> 构造函数：
> public static string ConfigFileBaseDir
> {
> get
> {
> #if !(NETSTANDARD1_0 || NETSTANDARD2_0)
> var configFileDir = ConfigurationManager.AppSettings["JiebaConfigFileDir"] ?? "Resources";
> if (!Path.IsPathRooted(configFileDir))
> {
> var domainDir = AppDomain.CurrentDomain.BaseDirectory;
> configFileDir = Path.GetFullPath(Path.Combine(domainDir, configFileDir));
> }
> #else
> var configFileDir = "Resources";
> #endif
> return configFileDir;
> }
> }
> 
> 上面已经写死了配置文件目录为：Resources ，无法使用自定义目录，导致初始化 JiebaSegmenter 实例的时候无法加载字典，是否考虑把初始化作为接口公开，由客户端决定何时何地使用任意目录进行字段目录的配置。
> 以方便加载字典和初始化实例。

我也遇到同样的问题，并且release项目后运行不了，程序直接退出

**Comment by xskingdeekis** [comment]
我也遇到同样的问题,项目自定义太差了；.net 4.0并且发布后运行直接闪退，debug模式就没有问题，估计构建也有问题

**Comment by anderscui** [comment]
@lianggx  请尝试一下新版本，jieba.NET自身也支持netcore了。
