### ISSUE TITLE
给一个案例，会抛出给定关键字不在字典中

### ISSUE THREAD

**Issue by starlightliu** [anderscui/jieba.NET#6]
var content = "元祐";
            var posSeg = new PosSegmenter();
            var ret = posSeg.Cut(content);

**Comment by anderscui** [comment]
@starlightliu 谢谢，我在看这个问题，POS标注过程中似乎有一个很细微的bug：）

**Comment by anderscui** [comment]
@starlightliu 已经修复了，更新到了NuGet。
