### ISSUE TITLE
这个分词等的来源都来自文件,我可否添加数据库支持

### ISSUE THREAD

**Issue by addisjeams** [anderscui/jieba.NET#62]
你好, 目前分词来源都来源于config或资源文件下的记事本
我想是否需要, 额外支持一下从db获取来源, 这样方便更新数据
如果作者你允许, 我会尝试添加以下功能

添加一个独立控制台, 直接回车(访问db的链接字符串直接写在app.config中)
负责生成orm简单的工厂模式代码
该控制台console引用SqlSugar生成访问数据库的代码
支持主流数据库的几张表作为来源

**Comment by anderscui** [comment]
@addisjeams 这样做似乎有点过于复杂了，我想你的需求是因为词典更新很频繁？如果是这样的建议使用 `LoadUserDict` 添加自定义词典，每次启动时从数据库读取词典，然后添加，这样和分词库两相独立：）
