### ISSUE TITLE
如何拆分数字，例如将53拆分为5,3,53三个词

### ISSUE THREAD

**Issue by rootlee88** [anderscui/jieba.NET#64]
如题

**Comment by anderscui** [comment]
@rootlee88 按现在的实现，这种拆分只能支持字数至少有3个的词。把"53"看作两个普通的汉字字符，我们一般不会希望把单个字切分出来。如果字数至少有3个，那么可以把词添加到词典来切分，使用的方法是 `CutForSearch`，我用 Python 版本的 jieba 试了一下是可以的：

```python
jieba.add_word('12345')
jieba.add_word('123')
print(list(jieba.cut_for_search('123456')))
```

但这样需要把所有数字都添加到词典，不可能实现，所以更好的方法还是后处理，在分词之后，单独处理一下数字。
