### ISSUE TITLE
自定义分词问题

### ISSUE THREAD

**Issue by iNuoers** [anderscui/jieba.NET#66]
自定义词库中有：最，最多。
分词的时候，这句：应用最多的，分不出最，只能分出最多

**Comment by anderscui** [comment]
@iNuoers 这种场景，长词需要至少三个字符，短词需要至少两个字符。比如“计算机”和“计算”可以同时切分出来，但“算”不可以。单字的情况，可以后处理一下。

**Comment by iNuoers** [comment]
自定义词组有点多，单字的就有几千个。那我在看下。
