### ISSUE TITLE
封装与MATLAB使用

### ISSUE THREAD

**Issue by cdzhjk001** [anderscui/jieba.NET#67]
因为一些个人习惯的原因，希望能在MATLAB中使用JIABA分词组件，目前简单研究的前提下，将目前的组件封装为DLL是较为方便形式，以下请教几个问题，1、我可以封装吗？（非商用，仅作为个人研究学习使用）；2、如果可以，是否有什么特殊的注意事项是我必须了解的？盼回！

**Comment by anderscui** [comment]
@cdzhjk001 
* 1、当然可以封装，欢迎使用：）
* 2、MIT许可协议是很宽松的，您可以稍微去了解一下。

**Comment by cdzhjk001** [comment]
非常感谢，那我先去试试看，如有问题，又再次向您请教。

**Comment by anderscui** [comment]
@cdzhjk001 不用客气，多多交流：）
