### ISSUE TITLE
想邀请您的项目在 Gitee 同步代码并加入 dotNET China 组织（非微软官方）

### ISSUE THREAD

**Issue by monksoul** [anderscui/jieba.NET#86]
大佬您好，我是 百小僧。我在 Gitee 联合了20个优秀的开源作者成立了 **dotNET China** 组织，目前正在寻找国内优秀的作者和项目加入，不知您是否有兴趣在 Gitee 创建仓库并同步 Github 代码。

这是我发起的国人 .NET 组织：https://gitee.com/dotnetchina，目前 QQ 群成员已经 7300人+

如果您对我还不了解，可以看看我的作品 Furion 框架：https://gitee.com/dotnetchina/Furion

最后，非常希望您的加入。

**Comment by 4Darmygeometry** [comment]
> 大佬您好，我是 百小僧。我在 Gitee 联合了20个优秀的开源作者成立了 **dotNET China** 组织，目前正在寻找国内优秀的作者和项目加入，不知您是否有兴趣在 Gitee 创建仓库并同步 Github 代码。
> 
> 这是我发起的国人 .NET 组织：https://gitee.com/dotnetchina，目前 QQ 群成员已经 7300人+
> 
> 如果您对我还不了解，可以看看我的作品 Furion 框架：https://gitee.com/dotnetchina/Furion
> 
> 最后，非常希望您的加入。

百小僧您好，我是 AOTba 作者，jieba.NET 的 AOT 兼容分支。

原版已多年未更新，存在 Emoji/生僻字/日期时间等拆分的已知问题，且具有Newtonsoft.Json漏洞。

AOTba 已解决这些问题，支持 GB18030-2022 级别3 和龙芯，具体特点如下：

支持三种分词模式：

精确模式，试图将句子最精确地切开，适合文本分析；

全模式，把句子中所有的可以成词的词语都扫描出来, 速度非常快，但是不能解决歧义。具体来说，分词过程不会借助于词频查找最大概率路径，亦不会使用HMM；

搜索引擎模式，在精确模式的基础上，对长词再次切分，提高召回率，适合用于搜索引擎分词。

支持繁体分词

支持添加自定义词典和自定义词

支持lcut与lcutforsearch直接返回列表

支持日期/时间完整提取不被拆开（如下午3点半、晚上8点30分、2021-01-01 09:00:00）

支持比例提取（如提取“金龙鱼1:1:1调和油”的“1:1:1”）

支持提取域名（如https://gitee.com/JTsamsde/AOTba ）

支持完整提取带下划线/短线单词（如TF-IDF）

支持版本号提取（如v1.0.1、1.0.1、3.2-preview1、4.1.2-rc1、2.1-alpha1、6.3-beta2）

支持异步加载词典

支持TF-IDF、TextRank算法关键词提取

支持日期、时间、链接、版本号等实体提取

支持含Emoji句子断句

支持带变体选择符和ZWJ的复杂emoji断句（甚至支持到Unicode 16的emoji）

支持开启或关闭实体保护，以便OpenCC.NET调用
全面支持GB18030-2022级别3及一号修改单要求（基本区到扩展I区汉字、〇及康熙部首处理能力）

可AOT编译

1.0.9及以前为 MIT 授权协议，1.0.10及以上为 Apache 2.0 与 MIT 双授权协议，可以商用闭源发布

是否有机会加入 dotNET China 组织，谢谢
