### ISSUE TITLE
同义支持

### ISSUE THREAD

**Issue by giszh86** [anderscui/jieba.NET#89]
你好，请问可以支持同义词吗？

**Comment by anderscui** [comment]
@zhongshuiyuan 项目中包含同义词词典，网上也能找到其它资源，自行替换实现吧：）

**Comment by giszh86** [comment]
> @zhongshuiyuan 项目中包含同义词词典，网上也能找到其它资源，自行替换实现吧：）

嗯，后来发现Lucene自带同义词
