### ISSUE TITLE
“JiebaNet.Segmenter.JiebaSegmenter”的类型初始值设定项引发异常

### ISSUE THREAD

**Issue by AaronMarsLuo** [anderscui/jieba.NET#9]
请问把整个Resources目录拷贝到程序集所在目录后直接写范例一的代码就行了吗？为什么会报错呢？

**Comment by anderscui** [comment]
https://github.com/anderscui/jieba.NET/issues/3，看看和这个issue一样吗？

**Comment by AaronMarsLuo** [comment]
@anderscui 是的，解决了，谢谢，我觉得可以把这个路径在哪加到主页的解释那里去

**Comment by yuzhouzhifengwfp** [comment]
@AaronMarsLuo  请问，那个路径到底在哪？我也没找到。

**Comment by yuzhouzhifengwfp** [comment]
@anderscui  请问，那个路径到底在哪？我也没找到。

**Comment by yuzhouzhifengwfp** [comment]
找到了，谢谢。
